<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SupplierController;
use Illuminate\Support\Facades\Route;

// Root redirect to products index
Route::get('/', function () {
    return redirect()->route('products.index');
});

// Dashboard (Auth Protected)
Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware(['auth'])
    ->name('dashboard');

// Public products index
Route::get('/products', [ProductController::class, 'index'])->name('products.index');

// Authenticated routes
Route::middleware('auth')->group(function () {

    // Profile management
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // 🗑 Trash Routes 
    Route::get('/products/trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::post('/products/{id}/restore', [ProductController::class, 'restore'])->name('products.restore');
    Route::delete('/products/{id}/force', [ProductController::class, 'forceDelete'])->name('products.forceDelete');

    // Products CRUD
    Route::resource('products', ProductController::class)->except(['index']);

    // Categories & Suppliers (read-only)
    Route::resource('categories', CategoryController::class)->only(['index']);
    Route::resource('suppliers', SupplierController::class)->only(['index']);
});

// Auth routes generated by Breeze
require __DIR__ . '/auth.php';
